const TRANSPORT = [
    {
        id: 'tr1',
        name: '9*6 пожарная машина',
        img: 'https://i.mycdn.me/i?r=AyH4iRPQ2q0otWIFepML2LxR7ATfMRcvnaWL7cN0Mxf41Q',
        price: 80,
    },
    {
        id: 'tr2',
        name: '9*5 грузовик',
        img: 'https://i.mycdn.me/i?r=AyH4iRPQ2q0otWIFepML2LxRnm9xJlTIgm9zsIv6okcnHw',
        price: 80,
    },
    {
        id: 'tr3',
        name: '9*5 мотоцикл',
        img: 'https://i.mycdn.me/i?r=AyH4iRPQ2q0otWIFepML2LxR7KwPV06kzK6nI_bTkB1CfA',
        price: 80,
    },
    {
        id: 'tr4',
        name: '9*5 самосвал',
        img: 'https://i.mycdn.me/i?r=AyH4iRPQ2q0otWIFepML2LxReljNKWZhkYP3zFHY4uHISA',
        price: 80,
    },
    {
        id: 'tr5',
        name: '9*4 порш',
        img: 'https://i.mycdn.me/i?r=AyH4iRPQ2q0otWIFepML2LxRyZmTRAj8P5Mvkz5HE7bkXg',
        price: 80,
    },
    {
        id: 'tr6',
        name: '9*5 маквин',
        img: 'https://i.mycdn.me/i?r=AyH4iRPQ2q0otWIFepML2LxRCs4P7a8rRoWhOZwHnCboZA',
        price: 80,
    },
    {
        id: 'tr7',
        name: '9*6 машинка',
        img: 'https://i.mycdn.me/i?r=AyH4iRPQ2q0otWIFepML2LxRSZ7-xQegA8BlISyyeIqgLg',
        price: 80,
    },
    {
        id: 'tr8',
        name: '9*6,5 машина',
        img: 'https://i.mycdn.me/i?r=AyH4iRPQ2q0otWIFepML2LxRAQWySlB4bAtI3bnUVfBxtg',
        price: 80,
    },
    {
        id: 'tr9',
        name: 'машинка 10*6',
        img: 'https://i.mycdn.me/i?r=AyH4iRPQ2q0otWIFepML2LxRnvpreHHdQqVgcjm5uP5iXw',
        price: 80,
    },
    {
        id: 'tr10',
        name: '8,5*6,5 пожарная машина',
        img: 'https://i.mycdn.me/i?r=AyH4iRPQ2q0otWIFepML2LxRc5nfZx3px7OZlpWtJ3UR1g',
        price: 80,
    },
    {
        id: 'tr11',
        name: '8,5*4 машина',
        img: 'https://i.mycdn.me/i?r=AzEnsT7vwF33wI5xm5ED0r61oQWX6_xJD8MbQHWZ99JMpYET9rmCpkHUMpVISbKYfv8',
        price: 80,
    },
    {
        id: 'tr12',
        name: '9*3,5 пикап',
        img: 'https://i.mycdn.me/i?r=AzEnsT7vwF33wI5xm5ED0r61oBX-kIZHs5SqKZnb-X_Np4ET9rmCpkHUMpVISbKYfv8',
        price: 80,
    },
    {
        id: 'tr13',
        name: '8*7,5 экскаватор',
        img: 'https://i.mycdn.me/i?r=AyH4iRPQ2q0otWIFepML2LxRdvOPaBRNmEwFzna7jPjW4A',
        price: 90,
    },
    {
        id: 'tr14',
        name: '9*8 машина',
        img: 'https://i.mycdn.me/i?r=AyH4iRPQ2q0otWIFepML2LxR10X_AYjNaVqITQh3NERVdQ',
        price: 80,
    },
    {
        id: 'tr15',
        name: '9*3,5 жук машина',
        img: 'https://i.mycdn.me/i?r=AyH4iRPQ2q0otWIFepML2LxRduiTZgwoZUFXA73D5lWlSA',
        price: 80,
    },
    {
        id: 'tr16',
        name: '11*8,5 тачка',
        img: 'https://i.mycdn.me/i?r=AyH4iRPQ2q0otWIFepML2LxRQeITOdQHKLy6J1HA9rjH_w',
        price: 200,
    },
    {
        id: 'tr17',
        name: '8*7,8 экскаватор',
        img: 'https://i.mycdn.me/i?r=AyH4iRPQ2q0otWIFepML2LxRSdMp12PoN2quvbAPjFAQEw',
        price: 80,
    },
    {
        id: 'tr18',
        name: '8*6 кар',
        img: 'https://i.mycdn.me/i?r=AyH4iRPQ2q0otWIFepML2LxRpdjZbVVExt1HI6u_NPVl9w',
        price: 80,
    },
    {
        id: 'tr19',
        name: '9*5 мотоцикл',
        img: 'https://i.mycdn.me/i?r=AyH4iRPQ2q0otWIFepML2LxR55VqlisD85pLXYeVWjk6fw',
        price: 80,
    },
    {
        id: 'tr20',
        name: '8*5 самосвал',
        img: 'https://i.mycdn.me/i?r=AyH4iRPQ2q0otWIFepML2LxRQrXciazS4XKBhc4ApVi74A',
        price: 80,
    },
    {
        id: 'tr21',
        name: 'самолет 9,5*7',
        img: 'https://i.mycdn.me/i?r=AyH4iRPQ2q0otWIFepML2LxRSuuf-lVeJmYcWDJF99QsEQ',
        price: 80,
    },
    {
        id: 'tr22',
        name: '9 см полицейская машина',
        img: 'https://i.mycdn.me/i?r=AyH4iRPQ2q0otWIFepML2LxR9IC_5Qm2cW2Y5SwOdh1dMg',
        price: 80,
    },
    {
        id: 'tr23',
        name: '9*6 корабль',
        img: 'https://i.mycdn.me/i?r=AyH4iRPQ2q0otWIFepML2LxRs7O7RbAbSNnVr_fw7Jwocg',
        price: 80,
    },
    {
        id: 'tr24',
        name: '8,5*6 вертолет',
        img: 'https://i.mycdn.me/i?r=AzEnsT7vwF33wI5xm5ED0r61DRTX6FyU85RCqBWuUuFQiIET9rmCpkHUMpVISbKYfv8',
        price: 80,
    },
    {
        id: 'tr25',
        name: 'парусник 19*14',
        img: 'https://i.mycdn.me/i?r=AyH4iRPQ2q0otWIFepML2LxRM5I6w5IGAZVhV0ivj-ZYMA',
        price: 300,
    },
    {
        id: 'tr26',
        name: '8*6 танк',
        img: 'https://i.mycdn.me/i?r=AyH4iRPQ2q0otWIFepML2LxRrCD1nazJgluiEgqbITWNlQ',
        price: 70,
    },
    {
        id: 'tr27',
        name: '10 см самолет',
        img: 'https://i.mycdn.me/i?r=AyH4iRPQ2q0otWIFepML2LxRj_TOL53VE5g9wzmQguCxCg',
        price: 190,
    },
    {
        id: 'tr28',
        name: '9*6,5 трактор',
        img: 'https://i.mycdn.me/i?r=AyH4iRPQ2q0otWIFepML2LxRPkZSJvRbC12PriWYer6sAw',
        price: 80,
    },
    {
        id: 'tr29',
        name: 'машинка 8 см по длине',
        img: 'https://i.mycdn.me/i?r=AzEnsT7vwF33wI5xm5ED0r61vNlqe9W_FDyaN4bSuQp--oET9rmCpkHUMpVISbKYfv8',
        price: 150,
    },
    {
        id: 'tr30',
        name: '10*13 см вырубка + трафарет',
        img: 'https://i.mycdn.me/i?r=AyH4iRPQ2q0otWIFepML2LxRM-6cY_ePs-O1JZIetdkRkQ',
        price: 190,
    },
    {
        id: 'tr31',
        name: 'вырубка 10*13см трафарет, набор',
        img: 'https://i.mycdn.me/i?r=AyH4iRPQ2q0otWIFepML2LxRkJ3OSZGEizFc7BsXDK4n8w',
        price: 170,
    },
    {
        id: 'tr32',
        name: '10,5см вырубка + трафарет набор "грузовик"',
        img: 'https://i.mycdn.me/i?r=AzEnsT7vwF33wI5xm5ED0r61ZoUlfPUx9soCHIbn3tRheIET9rmCpkHUMpVISbKYfv8',
        price: 130,
    },
    {
        id: 'tr33',
        name: '10 см вырубка+трафарет',
        img: 'https://i.mycdn.me/i?r=AzEnsT7vwF33wI5xm5ED0r61SIyjyktXeh6RTahU7XVD8oET9rmCpkHUMpVISbKYfv8',
        price: 140,
    },
    {
        id: 'tr34',
        name: '10,5 см вырубка + трафарет набор "Подъемный кран"',
        img: 'https://i.mycdn.me/i?r=AzEnsT7vwF33wI5xm5ED0r61Cy_FxyC-dEiiSW9lvzRwlIET9rmCpkHUMpVISbKYfv8',
        price: 140,
    },
    {
        id: 'tr35',
        name: '10см',
        img: 'https://i.mycdn.me/i?r=AzEnsT7vwF33wI5xm5ED0r61C-PoQGGQrwTg37r5brPlFoET9rmCpkHUMpVISbKYfv8',
        price: 200,
    },
    {
        id: 'tr36',
        name: 'самолет',
        img: 'https://i.mycdn.me/i?r=AzEnsT7vwF33wI5xm5ED0r61cF95fgMUsVTtf61JEpZ02oET9rmCpkHUMpVISbKYfv8',
        price: 350,
    },
    {
        id: 'tr37',
        name: '10 см',
        img: 'https://i.mycdn.me/i?r=AyH4iRPQ2q0otWIFepML2LxRYOkvly-tSu8ZhgcvrYqXmw',
        price: 190,
    },
    {
        id: 'tr38',
        name: '10 см танк',
        img: 'https://i.mycdn.me/i?r=AyH4iRPQ2q0otWIFepML2LxRJorMzKpS_OlrpzNytFEsdw',
        price: 190,
    },
    {
        id: 'tr39',
        name: '10см машина',
        img: 'https://i.mycdn.me/i?r=AyH4iRPQ2q0otWIFepML2LxRWjw6bpINBHNaRFcbFYwo-Q',
        price: 180,
    },
    {
        id: 'tr40',
        name: 'машинка 10см',
        img: 'https://i.mycdn.me/i?r=AyH4iRPQ2q0otWIFepML2LxRdWVwIPhTWXqryfv5Zf3WkA',
        price: 180,
    },
    {
        id: 'tr41',
        name: '10см',
        img: 'https://i.mycdn.me/i?r=AzEnsT7vwF33wI5xm5ED0r61bRlRhO4nOvszArY_rUEn0YET9rmCpkHUMpVISbKYfv8',
        price: 180,
    },
    {
        id: 'tr42',
        name: '12*8 см джип',
        img: 'https://i.mycdn.me/i?r=AzEnsT7vwF33wI5xm5ED0r61qecCSuu7_ptn6TlH1DstY4ET9rmCpkHUMpVISbKYfv8',
        price: 110,
    },
    {
        id: 'tr43',
        name: '10 см по крыльям самолет',
        img: 'https://i.mycdn.me/i?r=AzEnsT7vwF33wI5xm5ED0r61BDdIUFzEKzxQvKR6V6KdpoET9rmCpkHUMpVISbKYfv8',
        price: 90,
    },
]