const KONDITER = [
    {
        id: 'kp1',
        name: 'насадки на скалку(диаметр и толщина любые)',
        img: 'https://i.mycdn.me/i?r=AyH4iRPQ2q0otWIFepML2LxRdyOXa9GsOHhn1MJJ1_SlXA',
        price: 100,
    },
    {
        id: 'kp2',
        name: '0951 сеточка для айсинга 5*5 см размер клетки 4 мм*4 мм',
        img: 'https://i.mycdn.me/i?r=AyH4iRPQ2q0otWIFepML2LxRWAj4DH_YRkBkVQSsOBb9wg',
        price: 90,
    },
    {
        id: 'kp3',
        name: 'сеточка для айсинга 10*10 см размер клетки 4 мм*4 мм',
        img: 'https://i.mycdn.me/i?r=AzEnsT7vwF33wI5xm5ED0r619qPQJcHiPCfLx98s2ZcvFYET9rmCpkHUMpVISbKYfv8',
        price: 200,
    },
    {
        id: 'kp4',
        name: '2х2 мм, размер формы 8х8 см',
        img: 'https://i.mycdn.me/i?r=AyH4iRPQ2q0otWIFepML2LxRUByzgQkRh4E1uisaSNKPxQ',
        price: 180,
    },
    {
        id: 'kp5',
        name: 'держатель для трафарета',
        img: 'https://i.mycdn.me/i?r=AyH4iRPQ2q0otWIFepML2LxRtud7J7jN8KZJ31776dx5OA',
        price: 450,
    },
    {
        id: 'kp6',
        name: 'разделитель желтка от белка',
        img: 'https://i.mycdn.me/i?r=AyH4iRPQ2q0otWIFepML2LxRDe5gRXkMFu_y4NOLiH9yEg',
        price: 150,
    },
    {
        id: 'kp7',
        name: '№',
        img: 'https://i.mycdn.me/i?r=AyH4iRPQ2q0otWIFepML2LxRm-QfomJog3877wVKVMPDOA',
        price: 50,
    },
    {
        id: 'kp8',
        name: 'мешки 24,5*17 см 10шт',
        img: 'https://i.mycdn.me/i?r=AyH4iRPQ2q0otWIFepML2LxRkqIBPUrGj9lLdmpwQxURpQ',
        price: 40,
    },
    {
        id: 'kp9',
        name: 'высота 15 см ширина 8 см шпатель',
        img: 'https://i.mycdn.me/i?r=AyH4iRPQ2q0otWIFepML2LxRy6BDWkRzL9NwJ8_T8-Liag',
        price: 180,
    },
    {
        id: 'kp10',
        name: 'сетка 3*3 мм размер 15*15 см',
        img: 'https://i.mycdn.me/i?r=AzEnsT7vwF33wI5xm5ED0r61ZZUz_dLkbd3eX0bld1RG8oET9rmCpkHUMpVISbKYfv8',
        price: 300,
    },
    {
        id: 'kp11',
        name: '21*13 см пакетики 1шт',
        img: 'https://i.mycdn.me/i?r=AzEnsT7vwF33wI5xm5ED0r61G4nuiLDYX76JvtkfMvVY_YET9rmCpkHUMpVISbKYfv8',
        price: 7,
    },
    {
        id: 'kp12',
        name: 'высота 15 см ширина 8 см шпатель',
        img: 'https://i.mycdn.me/i?r=AyH4iRPQ2q0otWIFepML2LxRJNZiSLbK6NoifO634PUKGw',
        price: 180,
    },
    {
        id: 'kp13',
        name: 'высота 15 см ширина 8 см шпатель',
        img: 'https://i.mycdn.me/i?r=AyH4iRPQ2q0otWIFepML2LxRs0YW4BxWi5Wt-RU2OrJKDQ',
        price: 180,
    },
    {
        id: 'kp14',
        name: 'круги для вырезания канапе',
        img: 'https://i.mycdn.me/i?r=AyH4iRPQ2q0otWIFepML2LxRdaUdgWIYy8CzsmLk5owMNQ',
        price: 100,
    },
    {
        id: 'kp15',
        name: '#',
        img: 'https://i.mycdn.me/i?r=AzEnsT7vwF33wI5xm5ED0r614vvhIEN5r42hhNoiAnDVDIET9rmCpkHUMpVISbKYfv8',
        price: 300,
    },
    {
        id: 'kp16',
        name: '#',
        img: 'https://i.mycdn.me/i?r=AyH4iRPQ2q0otWIFepML2LxRlbuP0WKh_gDnqIuohylwgg',
        price: 300,
    },
    {
        id: 'kp17',
        name: 'Шпатель',
        img: 'https://i.mycdn.me/i?r=AyH4iRPQ2q0otWIFepML2LxRe5MsJfn3L-iJ-vXK4pffqQ',
        price: 150,
    },
]