const NABOR = [
    {
        id: 'n1',
        name: 'Cкай, роки, гонщик, зума , маршал 10 см',
        img: 'https://i.mycdn.me/i?r=AyH4iRPQ2q0otWIFepML2LxRwTR1GYk8ZFWTd5XrpOSfmw',
        price: 900,
    },
    {
        id: 'n2',
        name: 'Набор мимимишки',
        img: 'https://i.mycdn.me/i?r=AyH4iRPQ2q0otWIFepML2LxRZLRLbt_swyzX60ExbKrm8Q',
        price: 700,
    },
    {
        id: 'n3',
        name: 'желудь, лист клена, лист дуба, ежик 8см',
        img: 'https://i.mycdn.me/i?r=AyH4iRPQ2q0otWIFepML2LxRZcfNxVmb8aYogaB5RtAHNQ',
        price: 300,
    },
    {
        id: 'n4',
        name: 'Щенячий патруль+Райдер в подарок 10см',
        img: 'https://i.mycdn.me/i?r=AyH4iRPQ2q0otWIFepML2LxRda9S_c9F2a3Ibf2qLmx0aQ',
        price: 1550,
    },
    {
        id: 'n5',
        name: 'Набор шахматы(Король 4,5см)',
        img: 'https://i.mycdn.me/i?r=AyH4iRPQ2q0otWIFepML2LxRz1NxISP_8GHPO-R8fFrnaQ',
        price: 400,
    },
    {
        id: 'n6',
        name: 'снежинка, леденец, санта, варежка, елка, снеговик 9 см',
        img: 'https://i.mycdn.me/i?r=AyH4iRPQ2q0otWIFepML2LxRPWaBnCnCZ3npfcARTl-d0g',
        price: 500,
    },
    {
        id: 'n7',
        name: 'Набор Малышарики 10см',
        img: 'https://i.mycdn.me/i?r=AyH4iRPQ2q0otWIFepML2LxRWupeU2xFEFn1Op7hYHBKXQ',
        price: 900,
    },
    {
        id: 'n8',
        name: 'круг 14 см, елка 9 см, домик 10 см, снеговик 9 см',
        img: 'https://i.mycdn.me/i?r=AyH4iRPQ2q0otWIFepML2LxR8ppMEe3_EM_UPiyoAn1Rag',
        price: 340,
    },
    {
        id: 'n9',
        name: 'Набор',
        img: 'https://i.mycdn.me/i?r=AyH4iRPQ2q0otWIFepML2LxReyNLWZxp5FfvfyjV9IgPaA',
        price: 600,
    },
    {
        id: 'n10',
        name: 'скай, роки, гонщик, зума , крепыш, маршал 10 см',
        img: 'https://i.mycdn.me/i?r=AzEnsT7vwF33wI5xm5ED0r613BNwV5zq6-N-p24POwdLsIET9rmCpkHUMpVISbKYfv8',
        price: 1100,
    },
    {
        id: 'n11',
        name: 'Набор 8.5см',
        img: 'https://i.mycdn.me/i?r=AzEnsT7vwF33wI5xm5ED0r61DmfXFUS8GmITve4kp8sp24ET9rmCpkHUMpVISbKYfv8',
        price: 850,
    },
    {
        id: 'n12',
        name: 'Набор 10 см',
        img: 'https://i.mycdn.me/i?r=AzEnsT7vwF33wI5xm5ED0r61AlZ_4UEtHz7ToVUWzK4Gi4ET9rmCpkHUMpVISbKYfv8',
        price: 900,
    },
    {
        id: 'n13',
        name: 'Набор 10см',
        img: 'https://i.mycdn.me/i?r=AyH4iRPQ2q0otWIFepML2LxRAioSEk_oug_z-evAylSnpQ',
        price: 1400,
    },
    {
        id: 'n14',
        name: 'Набор из цветов 6см',
        img: 'https://i.mycdn.me/i?r=AyH4iRPQ2q0otWIFepML2LxRjk4GX4u5ppz_TfQjkZRgJw',
        price: 900,
    },
    {
        id: 'n15',
        name: 'Набор 10см',
        img: 'https://i.mycdn.me/i?r=AzEnsT7vwF33wI5xm5ED0r61uEgBCNTBM0e4xxysDwEtEIET9rmCpkHUMpVISbKYfv8',
        price: 1300,
    },
    {
        id: 'n16',
        name: 'Набор: 8см летающий, длинные 11см, остальные 10см',
        img: 'https://i.mycdn.me/i?r=AzEnsT7vwF33wI5xm5ED0r61rt0v9DNprSqFrme2IWfWeoET9rmCpkHUMpVISbKYfv8',
        price: 1600,
    },
    {
        id: 'n17',
        name: 'Набор',
        img: 'https://i.mycdn.me/i?r=AzEnsT7vwF33wI5xm5ED0r61qb-y7INlLKqWVC3O04orRoET9rmCpkHUMpVISbKYfv8',
        price: 1200,
    },
]